//! Web codegen backend — pixel-bearing pages composed from the bound design system.
//!
//! The C#/Kotlin backends pin behaviour; this target renders presentation:
//! one HTML page per UI step, composing **only** catalog CIOs (the closed
//! vocabulary, §4.5) resolved through the design system's reification rules,
//! styled exclusively through the emitted token custom properties (tokens,
//! not literals). Requires a How-bound design system — codegen gates on the
//! §11.2 coupling before a single page is emitted.

use crate::error::{ProductError, Result};

use super::decider::Decider;
use super::model::DomainGraph;
use super::model_ui::WireframeStep;
use super::projector::Projector;
use super::codegen::{gen, input_hash, provenance_json, GenFile, ReifyOptions, ReifyPlan};
use super::reify_ds::{css_var, ResolvedDs};

/// Plan the web projection: tokens + component base styles + one page per UI
/// step + the resolved `design-system.g.json`, all hash-pinned.
pub fn plan_web(
    graph: &DomainGraph,
    deciders: &[Decider],
    projectors: &[Projector],
    opts: &ReifyOptions,
) -> Result<ReifyPlan> {
    let Some(spec) = &opts.design_system else {
        return Err(ProductError::ConfigError(
            "the web backend needs a bound design system — `product design-system add <manifest>` then `product design-system bind <id>` (§4.5/§11)"
                .to_string(),
        ));
    };
    let graph_hash = input_hash(graph, &opts.product, deciders, projectors)?;
    let resolved = super::reify_ds::resolve(spec, graph)?;
    let mut sorted_p: Vec<&Projector> = projectors.iter().collect();
    sorted_p.sort_by(|a, b| a.id.cmp(&b.id));

    let mut files = vec![
        gen("tokens.g.css", super::reify_ds::tokens_css(spec)),
        gen("ds.g.css", base_css(spec)),
        gen("design-system.g.json", super::reify_ds::ds_json(&resolved, spec, &graph_hash)),
        gen("index.g.html", index_page(graph, &resolved)),
    ];
    for step in &graph.wireframe_steps {
        files.push(gen(
            &format!("pages/{}.g.html", step.id),
            step_page(step, &resolved, &sorted_p),
        ));
    }
    files.push(GenFile {
        path: "provenance.g.json".to_string(),
        content: provenance_json(opts, &graph_hash, &files),
        overwrite: true,
    });
    Ok(ReifyPlan { files, graph_hash, aggregates: Vec::new() })
}

/// Base component classes — one `.cio-<id>` per catalog component, every
/// declaration a token reference (`var(--…)`), never a literal.
fn base_css(spec: &super::reify_ds::DsSpec) -> String {
    let ds = &spec.manifest.design_system;
    let kind_of = |id: &str| ds.tokens.iter().find(|t| t.id == id).map(|t| t.kind.clone()).unwrap_or_default();
    let mut s = format!(
        "/* generated by `product codegen web` — design system '{}' v{}: on-system classes only */\n\
         @import url(\"tokens.g.css\");\nbody {{ margin: 0; font-family: system-ui, sans-serif; }}\n",
        ds.id, ds.version
    );
    for c in &ds.components {
        s.push_str(&format!(".cio-{} {{\n", c.id));
        for t in &c.tokens {
            s.push_str(&format!("  {}: var({});\n", css_property(t, &kind_of(t)), css_var(t)));
        }
        s.push_str("}\n");
    }
    s
}

/// The CSS property a token drives on its component, by token id + kind.
fn css_property(id: &str, kind: &str) -> &'static str {
    match kind {
        "color" if id.contains(".on-") => "color",
        "color" if id.contains("bg") || id.contains("accent") => "background-color",
        "color" => "color",
        "dimension" => "padding",
        "typography" => "font",
        _ => "--unmapped", // an unknown kind still resolves through a variable
    }
}

/// `index.g.html` — the entry: flows and their pages, plus the pinned identity.
fn index_page(graph: &DomainGraph, resolved: &ResolvedDs) -> String {
    let mut body = String::new();
    for flow in &graph.flows {
        body.push_str(&format!("  <section>\n    <h2>{}</h2>\n    <ol>\n", esc(&flow.label)));
        for step in &flow.steps {
            body.push_str(&format!(
                "      <li><a href=\"pages/{step}.g.html\">{}</a></li>\n",
                esc(step)
            ));
        }
        body.push_str("    </ol>\n  </section>\n");
    }
    if graph.flows.is_empty() {
        for step in &graph.wireframe_steps {
            body.push_str(&format!(
                "  <p><a href=\"pages/{}.g.html\">{}</a></p>\n",
                esc(&step.id),
                esc(&step.label)
            ));
        }
    }
    page_shell(
        "Reified screens",
        &format!("design system '{}' v{} — sha256:{}", esc(&resolved.id), esc(&resolved.version), resolved.hash),
        &body,
        "",
    )
}

/// One UI step realised as a page: sections per surface, buttons per offer —
/// each element carrying its resolved CIO class + graph vocabulary data
/// attributes, so on-system composition is checkable on the output.
fn step_page(step: &WireframeStep, resolved: &ResolvedDs, projectors: &[&Projector]) -> String {
    let comps = resolved.screens.get(&step.id).cloned().unwrap_or_default();
    let cio_for = |aio: &str, binds: &str| {
        comps
            .iter()
            .find(|c| c.aio == aio && c.binds == binds)
            .map(|c| (c.cio.clone(), c.context.clone()))
    };
    let mut body = String::new();
    for s in &step.surfaces {
        let Some((cio, ctx)) = cio_for(&s.aio, &s.projection) else { continue };
        body.push_str(&format!(
            "  <section class=\"cio-{cio}\" data-cio=\"{cio}\" data-aio=\"{}\" data-projection=\"{}\" data-context=\"{}\">\n    <h2>{}</h2>\n{}  </section>\n",
            esc(&s.aio), esc(&s.projection), esc(&ctx), esc(&s.projection), fixture_rows(step, projectors),
        ));
    }
    for o in &step.offers {
        let Some((cio, _)) = cio_for(&o.aio, &o.command) else { continue };
        body.push_str(&format!(
            "  <button class=\"cio-{cio}\" data-cio=\"{cio}\" data-aio=\"{}\" data-command=\"{}\">{}</button>\n",
            esc(&o.aio), esc(&o.command), esc(&o.command),
        ));
    }
    let mut nav = String::new();
    for next in &step.transitions_to {
        nav.push_str(&format!("    <a href=\"{}.g.html\">{}</a>\n", esc(next), esc(next)));
    }
    if !nav.is_empty() {
        body.push_str(&format!("  <nav>\n{nav}  </nav>\n"));
    }
    page_shell(&step.label, step.intent.as_deref().unwrap_or(""), &body, "../")
}

/// The present-state view data rendered as a definition list.
fn fixture_rows(step: &WireframeStep, projectors: &[&Projector]) -> String {
    let Some(view) = super::codegen_screen::present_state(step, projectors) else {
        return String::new();
    };
    let mut s = String::from("    <dl>\n");
    for (k, v) in &view {
        let val = match v {
            super::decider_logic::Scalar::Bool(b) => b.to_string(),
            super::decider_logic::Scalar::Int(i) => i.to_string(),
            super::decider_logic::Scalar::Str(t) => t.clone(),
        };
        s.push_str(&format!("      <dt>{}</dt><dd>{}</dd>\n", esc(k), esc(&val)));
    }
    s.push_str("    </dl>\n");
    s
}

fn page_shell(title: &str, subtitle: &str, body: &str, css_prefix: &str) -> String {
    format!(
        "<!doctype html>\n<!-- generated by `product codegen web` — do not edit; regenerate instead -->\n\
         <html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>{}</title>\n\
         <link rel=\"stylesheet\" href=\"{css_prefix}ds.g.css\">\n</head>\n<body>\n  <h1>{}</h1>\n{}{body}</body>\n</html>\n",
        esc(title),
        esc(title),
        if subtitle.is_empty() { String::new() } else { format!("  <p>{}</p>\n", esc(subtitle)) },
    )
}

fn esc(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
}

#[cfg(test)]
#[path = "codegen_web_tests.rs"]
mod tests;
