//! Task-type emission — the §5 cell that dispatches C# realisation work.
//!
//! `realise-csharp.cell.g.yaml` is built through the [`TaskType`] model
//! (valid by construction) and emitted into the reified tree, ready to be
//! copied into a blueprint's `cells/` directory. Its audits wire the three
//! deterministic gates — the generated xUnit scenario suite, `product
//! decider conform` over the generated runner, and the `codegen check`
//! drift gate — so a dispatched agent gets full construction freedom
//! inside an incorruptible definition of done.

use super::cell::{Audit, Cell, Slot, TaskType};
use crate::error::Result;

/// Render `realise-csharp.cell.g.yaml` for the generated tree.
pub fn cell_file(header_hash: &str, ns: &str, oracle_only: bool) -> Result<String> {
    let cell = task_type(ns, oracle_only);
    let yaml = cell.to_yaml()?;
    Ok(format!(
        "# <auto-generated/> by `product codegen csharp` — pf:graph-hash: sha256:{header_hash}\n# Copy into your blueprint's cells/ directory to dispatch realisation work units.\n{yaml}"
    ))
}

/// Render `realise-kotlin.cell.g.yaml` — the JVM realisation task type.
pub fn cell_file_kotlin(header_hash: &str, pkg: &str) -> Result<String> {
    let mut cell = task_type(pkg, true);
    cell.id = "realise-kotlin".to_string();
    cell.name = "Realise a Kotlin adapter seam against the reified oracle".to_string();
    cell.applies_when = "realising Deciders/Projectors/screens in Kotlin behind the oracle-only adapter seam (the What and How are frozen; the oracle artifacts are read-only)".to_string();
    if let Some(c) = cell.cells.first_mut() {
        c.artifact = "the conformance/projection/screen adapters plus your own realisation behind them".to_string();
        c.path = Some(format!("src/main/kotlin/{pkg}/ConformanceAdapter.kt"));
    }
    let runner = format!("build/install/{pkg}/bin/{pkg} <id>");
    for a in cell.audits.iter_mut() {
        a.checks = a
            .checks
            .replace("`dotnet test`", "`gradle test`")
            .replace(
                &format!("dotnet {pkg}.Conformance/bin/Debug/net8.0/{pkg}.Conformance.dll <decider>"),
                &runner,
            );
    }
    let yaml = cell.to_yaml()?;
    Ok(format!(
        "# <auto-generated/> by `product codegen kotlin` — pf:graph-hash: sha256:{header_hash}\n# Copy into your blueprint's cells/ directory to dispatch realisation work units.\n{yaml}"
    ))
}

fn task_type(ns: &str, oracle_only: bool) -> TaskType {
    TaskType {
        id: "realise-csharp".to_string(),
        name: "Realise a C# Decider against the reified oracle".to_string(),
        family: Some("application".to_string()),
        blueprint: None,
        classification: Some("core".to_string()),
        applies_when: "realising a §3.3 Decider in C# over a reified oracle tree (the What and How are frozen; the oracle artifacts are read-only)".to_string(),
        does_not_apply_when: Some(
            "the What or How needs to change — author the graph in a session instead, then regenerate with `product codegen csharp`".to_string(),
        ),
        slots: vec![
            slot("decider", "domain", "the decider id to realise", "which decider?",
                "the decider exists under .product/deciders and `product decider simulate` reports sound + complete"),
            slot("aggregate", "domain", "the aggregate (PascalCase) the decider decides for", "which aggregate?",
                "the aggregate entity exists in the What graph"),
        ],
        cells: vec![realise_cell(ns, oracle_only)],
        audits: audits(ns),
        deltas: None,
    }
}

fn slot(name: &str, kind: &str, dispatch: &str, capture: &str, audit: &str) -> Slot {
    Slot {
        name: name.to_string(),
        kind: Some(kind.to_string()),
        dispatch: dispatch.to_string(),
        capture: capture.to_string(),
        audit: audit.to_string(),
        required: true,
    }
}

fn realise_cell(ns: &str, oracle_only: bool) -> Cell {
    let (artifact, path) = if oracle_only {
        (
            "the conformance adapter plus your own domain model behind it (types, layering, patterns are yours)",
            format!("{ns}.Conformance/ConformanceAdapter.cs"),
        )
    } else {
        (
            "the Decide/Evolve implementation inside the generated partial frame",
            format!("{ns}.Domain/<aggregate>/<aggregate>Decider.cs"),
        )
    };
    Cell {
        id: "realise-decider".to_string(),
        artifact: artifact.to_string(),
        model: Some("code".to_string()),
        derived_from: vec!["domain:decider".to_string(), "oracle:scenario-tests".to_string()],
        applies: vec![],
        path: Some(path),
        edits: None,
    }
}

fn audits(ns: &str) -> Vec<Audit> {
    let runner =
        format!("dotnet {ns}.Conformance/bin/Debug/net8.0/{ns}.Conformance.dll <decider>");
    vec![
        Audit {
            id: "scenario-suite".to_string(),
            kind: Some("behavioural-conformance".to_string()),
            checks: "`dotnet test` passes every generated scenario fact (§6.3 — the oracle's second consumption)".to_string(),
            protects: "decider slot".to_string(),
        },
        Audit {
            id: "oracle-conform".to_string(),
            kind: Some("behavioural-conformance".to_string()),
            checks: format!(
                "`product decider conform <decider> --runner \"{runner}\"` reports behaviourally conformant"
            ),
            protects: "decider slot".to_string(),
        },
        Audit {
            id: "projection-conform".to_string(),
            kind: Some("behavioural-conformance".to_string()),
            checks: format!(
                "for each projector: `product projector conform <projector> --runner \"dotnet {ns}.Conformance/bin/Debug/net8.0/{ns}.Conformance.dll <projector>\"` reports conformant (§3.4 full-state equality)"
            ),
            protects: "the read-side fold (§3.4)".to_string(),
        },
        Audit {
            id: "screen-seam".to_string(),
            kind: Some("seam-conformance".to_string()),
            checks: "`dotnet test` passes every generated <Step>ScreenTests fact — each surfaced projection renders in every non-waived state, each offer is wired to its command (§4.5)".to_string(),
            protects: "the UI seam (§4.5)".to_string(),
        },
        Audit {
            id: "graph-drift".to_string(),
            kind: Some("provenance".to_string()),
            checks: "`product codegen check --out <reified dir>` exits 0 (generated oracle matches the current graph hash)".to_string(),
            protects: "the pinned graph hash (§7.3 provenance)".to_string(),
        },
    ]
}
