//! Static C# templates — runtime substrate, project files, provenance.
//!
//! The runtime (`Runtime.g.cs`) is the small, stable substrate every
//! generated aggregate targets: the command/event interfaces plus the
//! `DecisionResult` outcome (events or an invariant-id rejection — §3.3).
//! The wire protocol lives in `Oracle.g.cs` (`codegen_oracle`). Project
//! files pin `net8.0`; the test project pins the xUnit toolchain. All
//! templates are namespace-substituted, otherwise byte-fixed.

const RUNTIME_CS: &str = r##"#nullable enable

using System.Collections.Generic;

namespace {NS};

/// <summary>An intent from the What event model (§3.2) — handled by exactly one Decider.</summary>
public interface IDomainCommand
{
    /// <summary>The command's id in the What graph.</summary>
    string WireId { get; }
}

/// <summary>A past-tense fact from the What event model (§3.2).</summary>
public interface IDomainEvent
{
    /// <summary>The event's id in the What graph.</summary>
    string WireId { get; }

    /// <summary>The payload fields actually set, keyed by wire name (§6.3 protocol).</summary>
    IReadOnlyDictionary<string, object?> WirePayload();
}

/// <summary>The outcome of a decision (§3.3): emitted events, or a rejection naming the violated invariant.</summary>
public sealed class DecisionResult
{
    private DecisionResult(IReadOnlyList<IDomainEvent> events, string? rejected)
    {
        Events = events;
        RejectedInvariant = rejected;
    }

    public IReadOnlyList<IDomainEvent> Events { get; }

    /// <summary>The id of the invariant that rejected the command, or null when accepted.</summary>
    public string? RejectedInvariant { get; }

    public bool IsRejected => RejectedInvariant is not null;

    public static DecisionResult Emit(params IDomainEvent[] events) => new(events, null);

    public static DecisionResult Reject(string invariantId) => new(System.Array.Empty<IDomainEvent>(), invariantId);
}
"##;

const DOMAIN_CSPROJ: &str = r##"<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

</Project>
"##;

const CONFORMANCE_CSPROJ: &str = r##"<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../{NS}.Domain/{NS}.Domain.csproj" />
  </ItemGroup>

</Project>
"##;

const TESTS_CSPROJ: &str = r##"<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../{NS}.Domain/{NS}.Domain.csproj" />
  </ItemGroup>

</Project>
"##;

const README_MD: &str = r##"# {NS} — reified from the What graph

Generated by `product codegen csharp` from the `.product` What graph. Files
ending in `.g.cs` / `.g.yaml` / `.g.json` are regenerated on every run —
do not edit them. `<Aggregate>Decider.cs` files are editable stubs,
scaffolded once: author `Decide` + `Evolve` there (§3.3 behaviour is
realised, not transpiled).

## Verify (the same way the spec is verified)

1. `dotnet test` — every Decider scenario runs as an xUnit fact (§6.3).
2. Behavioural conformance against the oracle, per decider
   (build first so the runner's stdout stays protocol-clean):
   `dotnet build {NS}.Conformance` then
   `product decider conform <decider-id> --runner "dotnet {NS}.Conformance/bin/Debug/net8.0/{NS}.Conformance.dll <decider-id>"`
   The recorded verdict feeds `product deliverable done`.
3. Drift gate: `product codegen check --out <this directory>` fails when the
   What graph has moved past the graph hash stamped into this code
   (see `Provenance.g.cs` / `provenance.g.json`).

When the graph carries flows or UI steps, `<Ns>.Conformance.Tests` also
gains **flow facts** (each §3.2 chain replayed across both seams, with
every step's outcome baked by the oracle at generation time) and
**screen facts** (implement the scaffolded `ScreenAdapter` over your UI;
each surfaced projection must render in every non-waived state and each
offer must be wired to its command — §4.5).

`realise-csharp.cell.g.yaml` is a ready-made §5 task-type wiring these
gates as audits — copy it into your blueprint's `cells/` directory to
dispatch realisation work units over this tree.
"##;

const README_ORACLE_MD: &str = r##"# {NS} — What-graph oracle (adapter seam)

Generated by `product codegen csharp --oracle-only`. This tree carries **no
domain types** — you (or the realising agent) own the entire domain design:
types, layering, patterns per the How contract. The generated artifacts are
only the incorruptible definition of done:

- `{NS}.Conformance/Oracle.g.cs` — the wire-level seam: `WireEvent`,
  `WireCommand`, `ConformanceOutcome`, and `IConformanceAdapter`.
- `{NS}.Conformance/ConformanceAdapter.cs` — scaffolded once, never
  overwritten: implement it by delegating to your domain model (add your
  ProjectReference in the scaffolded csproj).
- `{NS}.Conformance.Tests/*.g.cs` — every Decider/Projector scenario as
  an xUnit fact at the wire level, plus flow facts (oracle-baked §3.2
  chains) and screen facts (implement `ScreenAdapter` over your UI).
- `Program.g.cs` — the `product decider conform` / `product projector
  conform` runner protocol.

## Verify

1. `dotnet test {NS}.Conformance.Tests`
2. `dotnet build {NS}.Conformance` then
   `product decider conform <decider-id> --runner "dotnet {NS}.Conformance/bin/Debug/net8.0/{NS}.Conformance.dll <decider-id>"`
3. `product codegen check --out <this directory>` — drift gate on the graph hash.

`realise-csharp.cell.g.yaml` is a ready-made §5 task-type wiring these
gates as audits for dispatched realisation work units.
"##;

/// `Runtime.g.cs` for the given namespace.
pub fn runtime_file(header: &str, ns: &str) -> String {
    format!("{header}{}", RUNTIME_CS.replace("{NS}", ns))
}

/// The three project files, namespace-substituted.
pub fn domain_csproj() -> String {
    DOMAIN_CSPROJ.to_string()
}

pub fn conformance_csproj(ns: &str) -> String {
    CONFORMANCE_CSPROJ.replace("{NS}", ns)
}

pub fn tests_csproj(ns: &str) -> String {
    TESTS_CSPROJ.replace("{NS}", ns)
}

/// The oracle-only test csproj — references the Conformance project (which
/// holds the adapter seam) instead of a generated Domain project.
pub fn oracle_tests_csproj(ns: &str) -> String {
    TESTS_CSPROJ
        .replace("{NS}.Domain/{NS}.Domain.csproj", "{NS}.Conformance/{NS}.Conformance.csproj")
        .replace("{NS}", ns)
}

/// `README.g.md` for the generated tree (mode-specific).
pub fn readme(ns: &str, oracle_only: bool) -> String {
    let t = if oracle_only { README_ORACLE_MD } else { README_MD };
    t.replace("{NS}", ns)
}

/// `Provenance.g.cs` — assembly metadata binding the built DLL to the exact
/// What it realises (§7.3): product, What version, graph content hash.
pub fn provenance_cs(header: &str, product: &str, what_version: &str, graph_hash: &str) -> String {
    use super::codegen_ident::cs_escape;
    format!(
        "{header}using System.Reflection;\n\n[assembly: AssemblyMetadata(\"PF.Product\", \"{}\")]\n[assembly: AssemblyMetadata(\"PF.WhatVersion\", \"{}\")]\n[assembly: AssemblyMetadata(\"PF.GraphHash\", \"sha256:{}\")]\n",
        cs_escape(product),
        cs_escape(what_version),
        graph_hash
    )
}
