//! Static C# templates — runtime substrate, project files, provenance.
//!
//! The runtime (`Runtime.g.cs`) is the small, stable substrate every
//! generated aggregate targets: the command/event interfaces, the
//! `DecisionResult` outcome (events or an invariant-id rejection — §3.3),
//! plus the JSON helpers of the §6.3 conformance wire protocol. Project
//! files pin `net8.0`; the test project pins the xUnit toolchain. All
//! templates are namespace-substituted, otherwise byte-fixed.

const RUNTIME_CS: &str = r##"#nullable enable

using System.Collections.Generic;
using System.Text.Json;

namespace {NS};

/// <summary>An intent from the What event model (§3.2) — handled by exactly one Decider.</summary>
public interface IDomainCommand
{
    /// <summary>The command's id in the What graph.</summary>
    string WireId { get; }
}

/// <summary>A past-tense fact from the What event model (§3.2).</summary>
public interface IDomainEvent
{
    /// <summary>The event's id in the What graph.</summary>
    string WireId { get; }

    /// <summary>The payload fields actually set, keyed by wire name (§6.3 protocol).</summary>
    IReadOnlyDictionary<string, object?> WirePayload();
}

/// <summary>The outcome of a decision (§3.3): emitted events, or a rejection naming the violated invariant.</summary>
public sealed class DecisionResult
{
    private DecisionResult(IReadOnlyList<IDomainEvent> events, string? rejected)
    {
        Events = events;
        RejectedInvariant = rejected;
    }

    public IReadOnlyList<IDomainEvent> Events { get; }

    /// <summary>The id of the invariant that rejected the command, or null when accepted.</summary>
    public string? RejectedInvariant { get; }

    public bool IsRejected => RejectedInvariant is not null;

    public static DecisionResult Emit(params IDomainEvent[] events) => new(events, null);

    public static DecisionResult Reject(string invariantId) => new(System.Array.Empty<IDomainEvent>(), invariantId);
}

/// <summary>JSON helpers for the §6.3 conformance wire protocol.</summary>
public static class PfJson
{
    /// <summary>Split a wire ref — a bare id string, or an object with the id under <paramref name="idKey"/> and an optional "with" payload.</summary>
    public static (string Id, JsonElement? With) Split(JsonElement el, string idKey)
    {
        if (el.ValueKind == JsonValueKind.String) return (el.GetString() ?? "", null);
        var id = el.GetProperty(idKey).GetString() ?? "";
        return el.TryGetProperty("with", out var with) ? (id, with) : (id, null);
    }

    public static long? GetLong(JsonElement? with, string name) =>
        with is { } w && w.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.Number ? v.GetInt64() : null;

    public static string? GetString(JsonElement? with, string name) =>
        with is { } w && w.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.String ? v.GetString() : null;

    public static bool? GetBool(JsonElement? with, string name) =>
        with is { } w && w.TryGetProperty(name, out var v) && (v.ValueKind == JsonValueKind.True || v.ValueKind == JsonValueKind.False) ? v.GetBoolean() : null;
}
"##;

const DOMAIN_CSPROJ: &str = r##"<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

</Project>
"##;

const CONFORMANCE_CSPROJ: &str = r##"<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../{NS}.Domain/{NS}.Domain.csproj" />
  </ItemGroup>

</Project>
"##;

const TESTS_CSPROJ: &str = r##"<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../{NS}.Domain/{NS}.Domain.csproj" />
  </ItemGroup>

</Project>
"##;

const README_MD: &str = r##"# {NS} — reified from the What graph

Generated by `product reify csharp` from the `.product` What graph. Files
ending in `.g.cs` / `.g.json` are regenerated on every run — do not edit
them. `<Aggregate>Decider.cs` files are editable stubs, scaffolded once:
author `Decide` + `Evolve` there (§3.3 behaviour is realised, not
transpiled).

## Verify (the same way the spec is verified)

1. `dotnet test` — every Decider scenario runs as an xUnit fact (§6.3).
2. Behavioural conformance against the oracle, per decider:
   `product decider conform <decider-id> --runner "dotnet run --project {NS}.Conformance -- <decider-id>"`
   The recorded verdict feeds `product deliverable done`.
3. Drift gate: `product reify check --out <this directory>` fails when the
   What graph has moved past the graph hash stamped into this code
   (see `Provenance.g.cs` / `provenance.g.json`).
"##;

/// `Runtime.g.cs` for the given namespace.
pub fn runtime_file(header: &str, ns: &str) -> String {
    format!("{header}{}", RUNTIME_CS.replace("{NS}", ns))
}

/// The three project files, namespace-substituted.
pub fn domain_csproj() -> String {
    DOMAIN_CSPROJ.to_string()
}

pub fn conformance_csproj(ns: &str) -> String {
    CONFORMANCE_CSPROJ.replace("{NS}", ns)
}

pub fn tests_csproj(ns: &str) -> String {
    TESTS_CSPROJ.replace("{NS}", ns)
}

/// `README.g.md` for the generated tree.
pub fn readme(ns: &str) -> String {
    README_MD.replace("{NS}", ns)
}

/// `Provenance.g.cs` — assembly metadata binding the built DLL to the exact
/// What it realises (§7.3): product, What version, graph content hash.
pub fn provenance_cs(header: &str, product: &str, what_version: &str, graph_hash: &str) -> String {
    use super::reify_ident::cs_escape;
    format!(
        "{header}using System.Reflection;\n\n[assembly: AssemblyMetadata(\"PF.Product\", \"{}\")]\n[assembly: AssemblyMetadata(\"PF.WhatVersion\", \"{}\")]\n[assembly: AssemblyMetadata(\"PF.GraphHash\", \"sha256:{}\")]\n",
        cs_escape(product),
        cs_escape(what_version),
        graph_hash
    )
}
