//! Reify orchestration — plan a verifiable C# projection of the What graph.
//!
//! Contract codegen only (no behaviour transpilation): typed records,
//! Decider frames, the scenario test suite, the §6.3 conformance runner,
//! provenance stamping. `plan_csharp` is pure — it returns the full file
//! set; the CLI adapter writes it. `input_hash` pins the exact inputs
//! (canonical Turtle + decider YAMLs) so `reify check` is a drift gate:
//! generated code that no longer matches the graph hash is stale.

use serde_json::json;

use crate::error::{ProductError, Result};

use super::decider::Decider;
use super::model::DomainGraph;
use super::provenance::content_hash;
use super::reify_decider::{adapter_file, frame_file, stub_file};
use super::reify_ident::pascal;
use super::reify_infer::{infer, AggShape};
use super::reify_program::{program_file, RunnerEntry};
use super::reify_runtime as runtime;
use super::reify_scenarios::tests_file;
use super::reify_types::{agg_types_file, domain_file};

/// Inputs the generator is parameterized by (all resolved by the adapter).
pub struct ReifyOptions {
    pub product: String,
    pub namespace: String,
    /// The What version this code realises (§7.3) — the How's
    /// `realises_version` when present, else `"unversioned"`.
    pub what_version: String,
    /// Oracle-only mode: emit no domain types — just the wire-level
    /// verification shell (`IConformanceAdapter` seam, scenario tests,
    /// runner, provenance). The realiser owns the whole domain design.
    pub oracle_only: bool,
}

/// One file of the plan. `overwrite: false` marks an editable scaffold the
/// adapter writes only when the file does not already exist.
pub struct GenFile {
    pub path: String,
    pub content: String,
    pub overwrite: bool,
}

/// The full deterministic file set for one `reify csharp` run.
pub struct ReifyPlan {
    pub files: Vec<GenFile>,
    pub graph_hash: String,
    pub aggregates: Vec<String>,
}

/// Hex SHA-256 over the canonical Turtle export plus every decider YAML
/// (sorted by id) — the identity `reify check` compares against.
pub fn input_hash(graph: &DomainGraph, product: &str, deciders: &[Decider]) -> Result<String> {
    let mut canon = graph.clone();
    super::seed_canon::canonicalize(&mut canon);
    let mut input = super::turtle::to_turtle(&canon, product);
    let mut sorted: Vec<&Decider> = deciders.iter().collect();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));
    for d in sorted {
        input.push('\0');
        input.push_str(&d.to_yaml()?);
    }
    Ok(content_hash(&input))
}

/// The banner every generated file opens with.
pub fn header(graph_hash: &str, what_version: &str) -> String {
    format!(
        "// <auto-generated/>\n// Generated by `product reify csharp` — do not edit; regenerate instead.\n// pf:graph-hash: sha256:{graph_hash}\n// pf:what-version: {what_version}\n\n"
    )
}

/// Plan the C# projection: domain types, one frame per Decider, the
/// conformance runner, the scenario tests, provenance.
pub fn plan_csharp(graph: &DomainGraph, deciders: &[Decider], opts: &ReifyOptions) -> Result<ReifyPlan> {
    let graph_hash = input_hash(graph, &opts.product, deciders)?;
    let hdr = header(&graph_hash, &opts.what_version);
    let mut sorted: Vec<&Decider> = deciders.iter().collect();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));
    let aggs = aggregate_names(&sorted)?;

    let mut files = if opts.oracle_only {
        oracle_global_files(opts, &hdr, &graph_hash)
    } else {
        global_files(graph, opts, &hdr, &graph_hash)
    };
    for (decider, agg) in sorted.iter().zip(&aggs) {
        let shape = infer(decider);
        files.extend(if opts.oracle_only {
            oracle_aggregate_files(opts, &hdr, decider, agg)
        } else {
            aggregate_files(graph, opts, &hdr, decider, agg, &shape)
        });
    }
    files.extend(conformance_files(opts, &hdr, &sorted, &aggs));
    files.push(gen(
        "realise-csharp.cell.g.yaml",
        super::reify_cell::cell_file(&graph_hash, &opts.namespace, opts.oracle_only)?,
    ));
    files.push(GenFile {
        path: "provenance.g.json".to_string(),
        content: provenance_json(opts, &graph_hash, &files),
        overwrite: true,
    });
    Ok(ReifyPlan { files, graph_hash, aggregates: aggs })
}

/// PascalCase aggregate names, one per decider — duplicates are an error
/// (two Deciders for one aggregate would collide on every generated type).
fn aggregate_names(sorted: &[&Decider]) -> Result<Vec<String>> {
    let mut seen = std::collections::BTreeSet::new();
    let mut out = Vec::new();
    for d in sorted {
        let agg = pascal(&d.decides_for);
        if !seen.insert(agg.clone()) {
            return Err(ProductError::ConfigError(format!(
                "deciders '{}' and another both decide for aggregate '{}' — one Decider per aggregate (§3.3)",
                d.id, d.decides_for
            )));
        }
        out.push(agg);
    }
    Ok(out)
}

fn global_files(graph: &DomainGraph, opts: &ReifyOptions, hdr: &str, hash: &str) -> Vec<GenFile> {
    let ns = &opts.namespace;
    let domain = format!("{ns}.Domain");
    vec![
        gen("README.g.md", runtime::readme(ns, false)),
        gen(&format!("{domain}/{domain}.csproj"), runtime::domain_csproj()),
        gen(&format!("{domain}/Runtime.g.cs"), runtime::runtime_file(hdr, ns)),
        gen(
            &format!("{domain}/Provenance.g.cs"),
            runtime::provenance_cs(hdr, &opts.product, &opts.what_version, hash),
        ),
        gen(&format!("{domain}/Domain.g.cs"), domain_file(hdr, ns, graph)),
    ]
}

/// Oracle-only globals — no domain project at all: the wire seam, the
/// scaffolded adapter + csproj (both realiser-owned), assembly provenance.
fn oracle_global_files(opts: &ReifyOptions, hdr: &str, hash: &str) -> Vec<GenFile> {
    let ns = &opts.namespace;
    let conf = format!("{ns}.Conformance");
    vec![
        gen("README.g.md", runtime::readme(ns, true)),
        GenFile {
            path: format!("{conf}/{conf}.csproj"),
            content: super::reify_oracle::oracle_csproj(),
            overwrite: false,
        },
        GenFile {
            path: format!("{conf}/ConformanceAdapter.cs"),
            content: super::reify_oracle::adapter_stub(ns),
            overwrite: false,
        },
        gen(
            &format!("{conf}/Provenance.g.cs"),
            runtime::provenance_cs(hdr, &opts.product, &opts.what_version, hash),
        ),
    ]
}

fn aggregate_files(
    graph: &DomainGraph,
    opts: &ReifyOptions,
    hdr: &str,
    decider: &Decider,
    agg: &str,
    shape: &AggShape,
) -> Vec<GenFile> {
    let ns = &opts.namespace;
    let dir = format!("{ns}.Domain/{agg}");
    let mut out = vec![
        gen(&format!("{dir}/{agg}Types.g.cs"), agg_types_file(hdr, ns, agg, graph, decider, shape)),
        gen(&format!("{dir}/{agg}Decider.g.cs"), frame_file(hdr, ns, agg, decider)),
        gen(&format!("{ns}.Conformance/{agg}Adapter.g.cs"), adapter_file(hdr, ns, agg, shape)),
        GenFile {
            path: format!("{dir}/{agg}Decider.cs"),
            content: stub_file(ns, agg, decider),
            overwrite: false,
        },
    ];
    if !decider.scenarios.is_empty() {
        out.push(gen(
            &format!("{ns}.Domain.Tests/{agg}ScenarioTests.g.cs"),
            tests_file(hdr, ns, agg, decider, shape),
        ));
    }
    out
}

/// Oracle-only per-decider artifacts: wire-level scenario facts only.
fn oracle_aggregate_files(opts: &ReifyOptions, hdr: &str, decider: &Decider, agg: &str) -> Vec<GenFile> {
    let ns = &opts.namespace;
    if decider.scenarios.is_empty() {
        return Vec::new();
    }
    vec![gen(
        &format!("{ns}.Conformance.Tests/{agg}ScenarioTests.g.cs"),
        super::reify_oracle::wire_tests_file(hdr, ns, agg, decider),
    )]
}

fn conformance_files(opts: &ReifyOptions, hdr: &str, sorted: &[&Decider], aggs: &[String]) -> Vec<GenFile> {
    let ns = &opts.namespace;
    let entries: Vec<RunnerEntry> = sorted
        .iter()
        .zip(aggs)
        .map(|(d, agg)| RunnerEntry { decider_id: d.id.clone(), agg: agg.clone() })
        .collect();
    let conf = format!("{ns}.Conformance");
    let mut out = vec![
        gen(&format!("{conf}/Oracle.g.cs"), super::reify_oracle::oracle_file(hdr, ns)),
        gen(
            &format!("{conf}/Program.g.cs"),
            program_file(hdr, ns, &entries, opts.oracle_only),
        ),
    ];
    if opts.oracle_only {
        out.push(gen(
            &format!("{ns}.Conformance.Tests/{ns}.Conformance.Tests.csproj"),
            runtime::oracle_tests_csproj(ns),
        ));
    } else {
        out.push(gen(&format!("{conf}/{conf}.csproj"), runtime::conformance_csproj(ns)));
        out.push(gen(
            &format!("{ns}.Domain.Tests/{ns}.Domain.Tests.csproj"),
            runtime::tests_csproj(ns),
        ));
    }
    out
}

fn gen(path: &str, content: String) -> GenFile {
    GenFile { path: path.to_string(), content, overwrite: true }
}

/// The machine-readable provenance manifest (`provenance.g.json`).
fn provenance_json(opts: &ReifyOptions, graph_hash: &str, files: &[GenFile]) -> String {
    let generated: Vec<&str> =
        files.iter().filter(|f| f.overwrite).map(|f| f.path.as_str()).collect();
    let v = json!({
        "product": opts.product,
        "namespace": opts.namespace,
        "what_version": opts.what_version,
        "graph_hash": format!("sha256:{graph_hash}"),
        "generator": "product reify csharp",
        "generated_files": generated,
    });
    let mut s = serde_json::to_string_pretty(&v).unwrap_or_default();
    s.push('\n');
    s
}

/// Extract the recorded graph hash from a `provenance.g.json` text.
pub fn recorded_hash(provenance: &str) -> Result<String> {
    let v: serde_json::Value = serde_json::from_str(provenance)
        .map_err(|e| ProductError::ConfigError(format!("invalid provenance.g.json: {e}")))?;
    v.get("graph_hash")
        .and_then(|h| h.as_str())
        .map(|h| h.trim_start_matches("sha256:").to_string())
        .ok_or_else(|| ProductError::ConfigError("provenance.g.json carries no graph_hash".to_string()))
}

#[cfg(test)]
#[path = "reify_tests.rs"]
mod tests;
