//! OpenAPI emission — the §4.4 interface contract generated from the model.
//!
//! One canonical REST projection of the event model, shared by every
//! reified system: each command becomes `POST /commands/{id}` (request
//! schema from the declared §3.2 payload fields, inference filling gaps;
//! 200 answers the emitted events, 409 a rejection naming the violated
//! invariant), each read model with a Projector becomes `GET /views/{id}`
//! (response schema from the view fields). Emitted as `openapi.g.json` in
//! every language tree — the wire both sides meet at, pinned to the same
//! graph hash, so client/server skew is structurally impossible.

use serde_json::{json, Map, Value};

use super::decider::Decider;
use super::model::DomainGraph;
use super::projector::Projector;
use super::reify_ident::CsTy;
use super::reify_infer::{infer_shape, Fields};
use super::reify_projector::infer_view;

/// Render `openapi.g.json` for the product.
pub fn openapi_file(
    graph: &DomainGraph,
    deciders: &[&Decider],
    projectors: &[&Projector],
    product: &str,
    what_version: &str,
    graph_hash: &str,
) -> String {
    let mut paths = Map::new();
    for d in deciders {
        let shape = infer_shape(d, graph);
        for (cmd, fields) in &shape.commands {
            paths.insert(format!("/commands/{cmd}"), command_path(graph, d, cmd, fields));
        }
    }
    for p in projectors {
        let (fields, _) = infer_view(p);
        paths.insert(format!("/views/{}", p.projects_for), view_path(p, &fields));
    }
    let doc = json!({
        "openapi": "3.0.3",
        "info": {
            "title": format!("{product} — interface contract"),
            "version": what_version,
            "description": "Generated by `product reify` from the What graph (§4.4) — do not edit; regenerate instead.",
            "x-pf-graph-hash": format!("sha256:{graph_hash}"),
            "x-pf-product": product,
        },
        "paths": Value::Object(paths),
        "components": { "schemas": {
            "Rejection": {
                "type": "object",
                "required": ["reject"],
                "properties": { "reject": { "type": "string", "description": "The violated invariant's id (§3.3)." } },
            },
        }},
    });
    let mut s = serde_json::to_string_pretty(&doc).unwrap_or_default();
    s.push('\n');
    s
}

fn command_path(graph: &DomainGraph, d: &Decider, cmd: &str, fields: &Fields) -> Value {
    let label = graph
        .commands
        .iter()
        .find(|c| c.id == cmd)
        .map(|c| c.label.clone())
        .unwrap_or_else(|| cmd.to_string());
    json!({
        "post": {
            "operationId": format!("post-{cmd}"),
            "summary": label,
            "description": format!("§3.2 command handled by decider '{}' (aggregate '{}').", d.id, d.decides_for),
            "requestBody": {
                "required": true,
                "content": { "application/json": { "schema": schema(fields) } },
            },
            "responses": {
                "200": {
                    "description": "Accepted — the §3.3 sanctioned events, in wire form.",
                    "content": { "application/json": { "schema": emitted_schema() } },
                },
                "409": {
                    "description": "Rejected by an invariant guard (§3.3).",
                    "content": { "application/json": { "schema": { "$ref": "#/components/schemas/Rejection" } } },
                },
            },
        }
    })
}

fn view_path(p: &Projector, fields: &Fields) -> Value {
    json!({
        "get": {
            "operationId": format!("get-{}", p.projects_for),
            "summary": format!("Read model '{}' (§3.4)", p.projects_for),
            "description": format!("Folded by projector '{}' from: {}.", p.id, p.folds.join(", ")),
            "responses": {
                "200": {
                    "description": "The view in wire form — oracle full-state semantics.",
                    "content": { "application/json": { "schema": schema(fields) } },
                },
            },
        }
    })
}

/// A JSON-Schema object over the wire scalar alphabet.
fn schema(fields: &Fields) -> Value {
    let mut props = Map::new();
    for (name, ty) in fields {
        props.insert(name.clone(), scalar_schema(*ty));
    }
    json!({ "type": "object", "properties": Value::Object(props), "additionalProperties": false })
}

fn scalar_schema(ty: Option<CsTy>) -> Value {
    match ty {
        Some(CsTy::Long) => json!({ "type": "integer", "format": "int64" }),
        Some(CsTy::Bool) => json!({ "type": "boolean" }),
        _ => json!({ "type": "string" }),
    }
}

fn emitted_schema() -> Value {
    json!({
        "type": "object",
        "required": ["emit"],
        "properties": { "emit": { "type": "array", "items": {
            "type": "object",
            "required": ["event"],
            "properties": {
                "event": { "type": "string" },
                "with": { "type": "object", "additionalProperties": true },
            },
        }}},
    })
}
