//! Agent context generation — AGENTS.md and schema output (ADR-031)

pub mod formal_schema;
pub mod schema;

pub use schema::{generate_all_schemas, generate_schema};

use crate::config::ProductConfig;
use crate::graph::KnowledgeGraph;
use crate::types::{FeatureStatus, TestStatus};
use std::path::Path;

// ---------------------------------------------------------------------------
// AGENTS.md generation
// ---------------------------------------------------------------------------

/// Generate the full AGENTS.md content from current repo state.
pub fn generate_agent_md(
    config: &ProductConfig,
    graph: &KnowledgeGraph,
    _repo_root: &Path,
) -> String {
    let agent_config = &config.agent_context;
    let version = env!("CARGO_PKG_VERSION");
    let timestamp = chrono::Utc::now().to_rfc3339();

    let mut out = String::new();
    out.push_str("# Product Agent Instructions\n\n");
    out.push_str(&format!("> Generated by product v{} | {}\n", version, timestamp));
    out.push_str("> Do not edit directly — regenerate with `product agent-init`\n\n");

    out.push_str(&generate_protocol_section());
    if agent_config.include_repo_state {
        out.push_str(&generate_repo_state_section(config, graph));
    }
    if agent_config.include_schemas {
        out.push_str(&generate_schemas_section());
    }
    if agent_config.include_domains {
        out.push_str(&generate_domains_section(config));
    }
    if agent_config.include_tool_guide {
        out.push_str(&generate_tool_guide_section());
    }
    out.push_str(&generate_ui_model_section());

    out
}

fn generate_protocol_section() -> String {
    r#"## Working Protocol

Before writing any specification content:
1. Call `product_graph_check` — understand current graph health
2. Call `product_graph_central` — identify the top-5 foundational ADRs
3. Call `product_feature_list` — understand what features exist
4. Call `product_context` on related features before scaffolding new ones

Never scaffold an artifact without first reading the graph.
Never write front-matter without consulting the schema below.

Requests with unknown top-level keys (anything other than
`type`, `schema-version`, `reason`, `artifacts`, `changes`) are rejected
with **E025**, not silently accepted. Mutation `field` values that do
not match a known front-matter field for the target artifact type are
rejected with **E026** — `product_request_apply` will not silently
no-op on a mistyped field name.

"#
    .to_string()
}

fn generate_repo_state_section(config: &ProductConfig, graph: &KnowledgeGraph) -> String {
    let proposed_adrs = graph.adrs.values()
        .filter(|a| a.front.status == crate::types::AdrStatus::Proposed).count();
    let passing = graph.tests.values().filter(|t| t.front.status == TestStatus::Passing).count();
    let failing = graph.tests.values().filter(|t| t.front.status == TestStatus::Failing).count();
    let unimpl = graph.tests.values()
        .filter(|t| t.front.status == TestStatus::Unimplemented).count();

    let mut phases: Vec<u32> = graph.features.values()
        .map(|f| f.front.phase).collect::<std::collections::HashSet<_>>()
        .into_iter().collect();
    phases.sort();

    let mut out = String::from("## Current Repository State\n\n");
    out.push_str(&format!("- {} features", graph.features.len()));
    if !phases.is_empty() {
        out.push_str(&format!(" across {} phases", phases.len()));
    }
    out.push('\n');
    for &p in &phases {
        out.push_str(&format_phase_line(config, graph, p));
    }
    out.push_str(&format!("- {} ADRs", graph.adrs.len()));
    if proposed_adrs > 0 { out.push_str(&format!(", {} proposed", proposed_adrs)); }
    out.push('\n');
    out.push_str(&format!(
        "- {} test criteria ({} passing, {} failing, {} unimplemented)\n",
        graph.tests.len(), passing, failing, unimpl
    ));
    if !graph.dependencies.is_empty() {
        out.push_str(&format!("- {} dependencies\n", graph.dependencies.len()));
    }
    out.push('\n');
    out
}

fn format_phase_line(config: &ProductConfig, graph: &KnowledgeGraph, phase: u32) -> String {
    let phase_features: Vec<_> = graph.features.values()
        .filter(|f| f.front.phase == phase).collect();
    let complete = phase_features.iter()
        .filter(|f| f.front.status == FeatureStatus::Complete).count();
    let total = phase_features.len();
    let gate_label = if graph.phase_gate_satisfied(phase).is_open() { "OPEN" } else { "LOCKED" };
    let phase_name = config.phases.get(&phase.to_string()).cloned().unwrap_or_default();
    if phase_name.is_empty() {
        format!("- Phase {}: {} ({}/{} complete)\n", phase, gate_label, complete, total)
    } else {
        format!("- Phase {} — {}: {} ({}/{} complete)\n", phase, phase_name, gate_label, complete, total)
    }
}

fn generate_schemas_section() -> String {
    let mut out = String::from("## Front-Matter Schemas\n\n");
    out.push_str("### Feature\n\n");
    out.push_str(&schema::feature_schema());
    out.push_str("\n\n### ADR\n\n");
    out.push_str(&schema::adr_schema());
    out.push_str("\n\n### Test Criterion\n\n");
    out.push_str(&schema::test_schema());
    out.push_str("\n\n### Dependency\n\n");
    out.push_str(&schema::dep_schema());
    out.push_str("\n\n");
    out
}

fn generate_domains_section(config: &ProductConfig) -> String {
    let mut out = String::from("## Domain Vocabulary\n\n");
    if config.domains.is_empty() {
        out.push_str("No domains configured in product.toml.\n\n");
    } else {
        let mut domains: Vec<_> = config.domains.keys().collect();
        domains.sort();
        let domain_list: Vec<String> = domains.iter().map(|d| d.to_string()).collect();
        out.push_str(&domain_list.join(", "));
        out.push_str("\n\n");
    }
    out
}

fn generate_tool_guide_section() -> String {
    r#"## Key MCP Tools

| Tool | When to use |
|---|---|
| `product_graph_central` | First call in any session — find foundational ADRs |
| `product_context` | Before implementing — assemble context bundle |
| `product_schema` | Get current front-matter schema for any type |
| `product_preflight` | Required at end of authoring — `status != clean` blocks implementation |
| `product_gap_check` | Before implementing — check spec completeness |
| `product_drift_check` | Before committing — check for spec/code drift |
| `product_agent_context` | Get full AGENTS.md content via MCP |
| `product_feature_depends_on` | Add or remove `depends-on` feature links — idempotent, cycle-checked |

## Implementation Workflow (FT-074)

`product implement FT-XXX` assembles the executor bundle and surfaces
three structural cues the agent must use:

- **Patterns.** The bundle's `## Patterns` section renders every PAT
  cited by `feature.patterns:` plus transitive prerequisites in topo
  order over `requires:`. Read patterns before TCs — they describe
  *how* to build this in this codebase.
- **TC `observes:` inline.** Each TC body carries an inline
  `**observes:** [...]` line listing the surfaces the test asserts
  against. Match your assertions to the declared surface(s) — file,
  graph, exit-code, tag, stdout, stderr, disk-state, or
  mcp-response.
- **ADR-051 hard constraint.** The `## Hard constraints` block
  carries a verbatim reminder: tests must assert against the named
  surface(s), never the response envelope alone.

Pass `--target legacy-template` to opt into the pre-FT-074 bundle
shape (no Patterns section, no inline observes, no ADR-051 line) —
useful when a custom prompt template omits the new variables.
"#
    .to_string()
}

// Split into two halves so each function stays within the function-length
// gate (the long raw string would otherwise count every line as a statement).
fn generate_ui_model_section() -> String {
    let mut out = generate_ui_model_what_section();
    out.push_str(&generate_ui_model_realisation_section());
    out
}

fn generate_ui_model_what_section() -> String {
    r#"## Framework UI Model (v1.2 — specified, implementation in progress)

The framework specifies UI as **What** (owned by product/design), kept
structurally separate from **How** (realisation). When a feature touches
screens, model these artifacts in the `pf:` What graph — never free-text
descriptions:

- **UI step** — the What of a screen, typed against **Abstract Interaction
  Objects (AIOs)** (`single-select`, `trigger-action`, `text-entry`,
  `display-value`, `display-collection`, `navigate`, `edit`) — never a concrete
  control (a dropdown, a button). It declares the projection it *surfaces*, the
  commands it *offers*, its *transitions*, its *emphasis*, a *meaning for every
  state* of each surfaced projection, its *accessibility obligations* (WCAG 2.2
  criteria), and its *content references* (by key + role, never literal copy).
- **Context of use** — form factor / modality, declared as What-side facts; the
  parameter reification rules are written against.
- **Read-model state space** — `present` plus any of `loading`/`empty`/`failed`;
  a UI step must give a meaning to every state it can be in or waive it with a
  reason (state coverage — the UI analogue of Decider command coverage).

"#
    .to_string()
}

fn generate_ui_model_realisation_section() -> String {
    r#"- **Content** — authored words carried by **content key + role**
  (heading / body / empty-message / error-message / help / legal), resolved by
  the How against a **content store** parameterised by **locale**. Never a
  literal string in the What.
- **CIO / reification (How)** — a design system supplies **Concrete Interaction
  Objects**; `reify(AIO, context) -> CIO` rules (carrying rationale) bind each
  AIO to an on-system component per context. Styling is tokens, not literals.
- **Page graph** — navigation is one graph: pages are nodes, `navigate`
  transitions are edges, a flow is a named subgraph with an entry page, and the
  application root's out-edges are the global destinations ("top-level" is
  derived, not tagged).
- **Seam verification** — confirms a screen and its UI step agree: every datum
  projected, every control a valid command, reification / state / content
  coverage, accessibility discharged.

The four "do not bake the concrete thing into the What" moves are uniform:
widgets -> AIOs, styles -> tokens, components -> CIOs, copy -> content
references.

**Status:** this model is specified in FT-134..FT-142 / ADR-078..ADR-085
(phase 7) and being implemented. Today the What-capture session records UI
steps via `add_wireframe_step`; typed AIO / content / reification / seam capture
lands with those features. Author UI features to this model so they are ready
when the tooling catches up.

"#
    .to_string()
}

// ---------------------------------------------------------------------------
// Watch mode — regenerate AGENTS.md on file changes
// ---------------------------------------------------------------------------

/// Watch for changes in artifact directories and regenerate AGENTS.md.
pub fn watch_and_regenerate(
    config: &ProductConfig,
    repo_root: &std::path::Path,
) -> Result<(), Box<dyn std::error::Error>> {
    use notify::{Config, Event, RecommendedWatcher, RecursiveMode, Watcher};
    use std::sync::mpsc;
    use std::time::Duration;

    let (tx, rx) = mpsc::channel::<Result<Event, notify::Error>>();
    let mut watcher = RecommendedWatcher::new(
        move |res| { let _ = tx.send(res); },
        Config::default().with_poll_interval(Duration::from_secs(1)),
    )?;

    let dirs = [
        config.resolve_path(repo_root, &config.paths.features),
        config.resolve_path(repo_root, &config.paths.adrs),
        config.resolve_path(repo_root, &config.paths.tests),
        config.resolve_path(repo_root, &config.paths.dependencies),
    ];
    for dir in &dirs {
        if dir.exists() {
            watcher.watch(dir, RecursiveMode::Recursive)?;
        }
    }
    if let Some(cfg) = crate::config::find_config_in_dir(repo_root) {
        watcher.watch(&cfg, RecursiveMode::NonRecursive)?;
    }

    eprintln!("Watching for changes... (press Ctrl+C to stop)");
    regenerate(repo_root)?;

    loop {
        match rx.recv() {
            Ok(Ok(_event)) => {
                while rx.try_recv().is_ok() {}
                std::thread::sleep(Duration::from_millis(200));
                match regenerate(repo_root) {
                    Ok(()) => eprintln!("AGENTS.md regenerated"),
                    Err(e) => eprintln!("Regeneration error: {}", e),
                }
            }
            Ok(Err(e)) => eprintln!("Watch error: {}", e),
            Err(_) => break,
        }
    }
    Ok(())
}

/// Regenerate AGENTS.md from current repo state.
fn regenerate(repo_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let cfg_path = crate::config::find_config_in_dir(repo_root).ok_or_else(|| {
        crate::error::ProductError::ConfigError(format!(
            "no product config found under {}",
            repo_root.display()
        ))
    })?;
    let config = ProductConfig::load(&cfg_path)?;
    let features_dir = config.resolve_path(repo_root, &config.paths.features);
    let adrs_dir = config.resolve_path(repo_root, &config.paths.adrs);
    let tests_dir = config.resolve_path(repo_root, &config.paths.tests);
    let deps_dir = config.resolve_path(repo_root, &config.paths.dependencies);

    let loaded =
        crate::parser::load_all_with_deps(&features_dir, &adrs_dir, &tests_dir, Some(&deps_dir))?;
    let graph = KnowledgeGraph::build_with_deps(
        loaded.features, loaded.adrs, loaded.tests, loaded.dependencies,
    );
    let content = generate_agent_md(&config, &graph, repo_root);
    let output_path = repo_root.join(&config.agent_context.output_file);
    crate::fileops::write_file_atomic(&output_path, &content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn protocol_section_contains_mcp_calls() {
        let section = generate_protocol_section();
        assert!(section.contains("product_graph_check"));
        assert!(section.contains("product_graph_central"));
        assert!(section.contains("product_feature_list"));
        assert!(section.contains("product_context"));
    }

    #[test]
    fn tool_guide_contains_key_tools() {
        let section = generate_tool_guide_section();
        assert!(section.contains("product_context"));
        assert!(section.contains("product_schema"));
        assert!(section.contains("product_graph_central"));
        assert!(section.contains("product_preflight"));
        assert!(section.contains("product_gap_check"));
        assert!(section.contains("product_drift_check"));
        assert!(section.contains("product_agent_context"));
    }

    #[test]
    fn ui_model_section_teaches_the_v1_2_artifacts() {
        let section = generate_ui_model_section();
        assert!(section.contains("Abstract Interaction"));
        assert!(section.contains("AIOs"));
        assert!(section.contains("reify(AIO, context)"));
        assert!(section.contains("content store"));
        assert!(section.contains("Seam verification"));
        assert!(section.contains("Page graph"));
        // Honest about what is callable today vs specified.
        assert!(section.contains("add_wireframe_step"));
        assert!(section.contains("FT-134..FT-142"));
    }
}
