//! Checklist generation (ADR-007)

use crate::graph::KnowledgeGraph;
use crate::types::*;

/// Generate checklist.md from current graph state
pub fn generate(graph: &KnowledgeGraph) -> String {
    let mut out = String::new();
    out.push_str("# Implementation Checklist\n\n");
    out.push_str(&format!(
        "> Generated by product v0.1 | Last updated: {}\n",
        chrono::Utc::now().format("%Y-%m-%d")
    ));
    out.push_str("> Do not edit directly — update status in feature/test front-matter and run `product checklist generate`\n\n");

    // Group features by phase, sorted by topo order if possible
    let order = graph.topological_sort().unwrap_or_else(|_| {
        let mut ids: Vec<String> = graph.features.keys().cloned().collect();
        ids.sort();
        ids
    });

    // Collect phases
    let mut phases: Vec<u32> = graph
        .features
        .values()
        .map(|f| f.front.phase)
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();
    phases.sort();

    for phase in &phases {
        out.push_str(&format!("## Phase {}\n\n", phase));

        let phase_features: Vec<&String> = order
            .iter()
            .filter(|id| {
                graph
                    .features
                    .get(id.as_str())
                    .map(|f| f.front.phase == *phase)
                    .unwrap_or(false)
            })
            .collect();

        for fid in phase_features {
            if let Some(f) = graph.features.get(fid.as_str()) {
                let status_marker = match f.front.status {
                    FeatureStatus::Complete => "[x]",
                    FeatureStatus::InProgress => "[~]",
                    FeatureStatus::Planned => "[ ]",
                    FeatureStatus::Abandoned => "[-]",
                };
                out.push_str(&format!(
                    "### {} — {} {}\n\n",
                    f.front.id,
                    f.front.title,
                    status_marker
                ));

                // List ADRs
                for adr_id in &f.front.adrs {
                    if let Some(adr) = graph.adrs.get(adr_id.as_str()) {
                        let marker = match adr.front.status {
                            AdrStatus::Accepted => "[x]",
                            AdrStatus::Proposed => "[ ]",
                            AdrStatus::Superseded => "[-]",
                            AdrStatus::Abandoned => "[-]",
                        };
                        out.push_str(&format!(
                            "- {} {}: {} ({})\n",
                            marker, adr.front.id, adr.front.title, adr.front.status
                        ));
                    }
                }

                // List tests
                for test_id in &f.front.tests {
                    if let Some(tc) = graph.tests.get(test_id.as_str()) {
                        let marker = match tc.front.status {
                            TestStatus::Passing => "[x]",
                            TestStatus::Implemented => "[~]",
                            TestStatus::Unimplemented => "[ ]",
                            TestStatus::Failing => "[!]",
                        };
                        out.push_str(&format!(
                            "- {} {}: {} ({}) — {}\n",
                            marker, tc.front.id, tc.front.title, tc.front.test_type, tc.front.status
                        ));
                    }
                }

                out.push('\n');
            }
        }
    }

    out
}
